version: 0.2

phases:
  install:
    commands: 
      - npm ci
    

  build: 
    commands:
      - npm run build

  post_build: 
    commands:
      - cd public/ && aws s3 sync . s3://blog.mastertheclouds.com/
